import { OilfieldName, PhaseOutSchedule } from "../data/gameData";
import { mdgPlan } from "../generated/dataMdg";
import { Year } from "../data/types";
import {
  computeFieldStats,
  cumulativeEmissions,
  emissionsFromYear,
  FieldStat,
  productionFromYear,
} from "./fieldStats";
import { formatCompactNumber } from "./emissionEquivalents";

/** A single piece of generated advice or analysis. */
export type Insight = {
  kind: "success" | "warning" | "tip" | "info";
  emoji: string;
  title: string;
  text: string;
};

/** The complete analysis of a phase-out plan, generated by the advisor. */
export type AdvisorReport = {
  /** Letter grade for the plan, from A+ to F */
  grade: string;
  gradeComment: string;
  /** Natural language executive summary of the plan */
  summary: string;
  insights: Insight[];
  /** Cumulative avoided emissions 2025–2040 @unit tCO₂e */
  avoidedEmission: number;
  /** Avoided emissions as percentage of the baseline */
  reductionPercent: number;
  /** MDG's plan reduction percentage, for comparison */
  mdgReductionPercent: number;
};

function formatMt(tonnes: number): string {
  const mt = tonnes / 1_000_000;
  if (mt >= 10) return `${Math.round(mt)} millioner tonn`;
  if (mt >= 0.1)
    return `${(Math.round(mt * 10) / 10).toLocaleString("nb-NO")} millioner tonn`;
  return `${formatCompactNumber(tonnes)} tonn`;
}

function gradeForRatio(ratio: number): { grade: string; comment: string } {
  if (ratio >= 1.15)
    return {
      grade: "A+",
      comment:
        "Planen din kutter mer enn MDGs egen utfasingsplan. Imponerende!",
    };
  if (ratio >= 1)
    return {
      grade: "A",
      comment: "Planen din er på nivå med MDGs utfasingsplan. Sterkt levert!",
    };
  if (ratio >= 0.85)
    return {
      grade: "B",
      comment: "Planen din er nesten like ambisiøs som MDGs utfasingsplan.",
    };
  if (ratio >= 0.65)
    return {
      grade: "C",
      comment: "En god start, men det er fortsatt mye å hente.",
    };
  if (ratio >= 0.45)
    return {
      grade: "D",
      comment: "Planen din monner, men klimaet trenger raskere kutt.",
    };
  if (ratio >= 0.2)
    return {
      grade: "E",
      comment: "Du har så vidt begynt. De store utslippskuttene gjenstår.",
    };
  return {
    grade: "F",
    comment: "Nesten alle utslippene fortsetter som før. På tide å handle!",
  };
}

/**
 * Analyzes a phase-out plan and generates a report with a grade and a list of
 * natural language insights in Norwegian.
 *
 * The analysis is fully deterministic and runs locally on the game's dataset:
 * it compares the plan against the do-nothing baseline and MDG's reference
 * plan, and looks for patterns such as high-intensity fields left running or
 * early phase-out of the worst emitters.
 *
 * @param phaseOut - The player's committed phase-out schedule.
 * @param currentYear - The current in-game year, used to suggest realistic
 *   phase-out years for the advice.
 */
export function analyzePlan(
  phaseOut: PhaseOutSchedule,
  currentYear: Year,
): AdvisorReport {
  const stats = computeFieldStats();
  const baselineEmission = cumulativeEmissions({});
  const planEmission = cumulativeEmissions(phaseOut);
  const mdgEmission = cumulativeEmissions(mdgPlan);

  const avoidedEmission = baselineEmission - planEmission;
  const mdgAvoided = baselineEmission - mdgEmission;
  const reductionPercent = Math.round(
    (avoidedEmission / baselineEmission) * 100,
  );
  const mdgReductionPercent = Math.round((mdgAvoided / baselineEmission) * 100);
  const ratio = mdgAvoided > 0 ? avoidedEmission / mdgAvoided : 0;

  const { grade, comment: gradeComment } = gradeForRatio(ratio);

  const shelfAverageIntensity =
    stats.reduce((sum, s) => sum + s.avgIntensity * s.totalProduction, 0) /
    stats.reduce((sum, s) => sum + s.totalProduction, 0);

  const phasedOutFields = stats.filter((s) => phaseOut[s.field]);
  const runningFields = stats.filter((s) => !phaseOut[s.field]);

  const insights: Insight[] = [];

  // 1. Getting started: no fields phased out yet
  if (phasedOutFields.length === 0) {
    const worst = stats.slice(0, 3);
    insights.push({
      kind: "tip",
      emoji: "🧭",
      title: "Start med verstingene",
      text:
        `Ingen felter er faset ut ennå. De mest forurensende feltene per fat er ` +
        worst
          .map(
            (s) =>
              `${s.field} (${s.avgIntensity.toLocaleString("nb-NO")} kg CO₂/fat)`,
          )
          .join(", ") +
        `. Gjennomsnittet på sokkelen er ${(Math.round(shelfAverageIntensity * 10) / 10).toLocaleString("nb-NO")} kg CO₂/fat – å starte der gir mest klimaeffekt for hvert fat olje som fases ut.`,
    });
  }

  // 2. High-intensity fields still running
  const dirtyRunning = runningFields
    .filter((s) => s.avgIntensity > shelfAverageIntensity * 1.5)
    .slice(0, 3);
  if (dirtyRunning.length > 0 && phasedOutFields.length > 0) {
    const potential = dirtyRunning
      .map((s) => emissionsFromYear(s.field, currentYear))
      .reduce((a, b) => a + b, 0);
    insights.push({
      kind: "warning",
      emoji: "⚠️",
      title: "Utslippsverstinger går fortsatt for fullt",
      text:
        dirtyRunning.map((s) => s.field).join(", ") +
        ` har ${dirtyRunning.length > 1 ? "utslippsintensitet" : "en utslippsintensitet"} langt over sokkel-snittet, men er ikke faset ut i planen din. ` +
        `Fases ${dirtyRunning.length > 1 ? "disse" : "feltet"} ut i ${currentYear}, unngås ytterligere ${formatMt(potential)} CO₂ frem mot 2040.`,
    });
  }

  // 3. Praise good choices: dirty fields phased out early
  const goodChoices = phasedOutFields
    .filter((s) => s.avgIntensity > shelfAverageIntensity * 1.3)
    .sort(
      (a, b) =>
        emissionsFromYear(b.field, phaseOut[b.field]!) -
        emissionsFromYear(a.field, phaseOut[a.field]!),
    )
    .slice(0, 3);
  if (goodChoices.length > 0) {
    const saved = goodChoices
      .map((s) => emissionsFromYear(s.field, phaseOut[s.field]!))
      .reduce((a, b) => a + b, 0);
    insights.push({
      kind: "success",
      emoji: "✅",
      title: "Godt valg av felter",
      text:
        `Du har faset ut ${goodChoices.map((s) => `${s.field} (${phaseOut[s.field]})`).join(", ")} – ` +
        `${goodChoices.length > 1 ? "felter" : "et felt"} med langt høyere utslipp per fat enn snittet. Det alene unngår ${formatMt(saved)} CO₂.`,
    });
  }

  // 4. Inefficient choices: very clean fields phased out while dirty ones run
  const cleanPhasedOut = phasedOutFields.filter(
    (s) => s.avgIntensity < shelfAverageIntensity * 0.6,
  );
  if (cleanPhasedOut.length > 0 && dirtyRunning.length > 0) {
    const example = cleanPhasedOut[0];
    insights.push({
      kind: "tip",
      emoji: "⚖️",
      title: "Prioriter skitne felter først",
      text:
        `${example.field} er blant de renere feltene (${example.avgIntensity.toLocaleString("nb-NO")} kg CO₂/fat), men er faset ut mens ${dirtyRunning[0].field} ` +
        `(${dirtyRunning[0].avgIntensity.toLocaleString("nb-NO")} kg CO₂/fat) fortsatt produserer. Bytter du rekkefølgen, får du større utslippskutt for samme produksjonstap.`,
    });
  }

  // 5. Comparison with MDG's plan: biggest divergence where the player is later
  const divergences = stats
    .map((s) => {
      const mdgYear = mdgPlan[s.field];
      const userYear = phaseOut[s.field];
      if (!mdgYear) return undefined;
      const effectiveUserYear = userYear ? parseInt(userYear) : 2041;
      const gap = effectiveUserYear - parseInt(mdgYear);
      if (gap < 3) return undefined;
      const extraEmission =
        emissionsFromYear(s.field, mdgYear) -
        (userYear ? emissionsFromYear(s.field, userYear) : 0);
      return { stat: s, mdgYear, userYear, gap, extraEmission };
    })
    .filter((d): d is NonNullable<typeof d> => !!d)
    .sort((a, b) => b.extraEmission - a.extraEmission);
  if (divergences.length > 0 && phasedOutFields.length > 0) {
    const d = divergences[0];
    insights.push({
      kind: "info",
      emoji: "📊",
      title: `MDG faser ut ${d.stat.field} tidligere`,
      text:
        `I MDGs plan avvikles ${d.stat.field} i ${d.mdgYear}` +
        (d.userYear
          ? `, mens din plan venter til ${d.userYear}.`
          : `, mens din plan lar feltet produsere videre.`) +
        ` Forskjellen utgjør ${formatMt(d.extraEmission)} CO₂.`,
    });
  }

  // 6. Production perspective: how much production the plan forgoes
  if (phasedOutFields.length > 0) {
    const baselineProduction = stats.reduce(
      (sum, s) => sum + s.totalProduction,
      0,
    );
    const forgone = phasedOutFields
      .map((s) => productionFromYear(s.field, phaseOut[s.field]!))
      .reduce((a, b) => a + b, 0);
    const forgonePercent = Math.round((forgone / baselineProduction) * 100);
    insights.push({
      kind: "info",
      emoji: "🛢️",
      title: "Klimaeffekt per fat",
      text:
        `Planen din kutter ${reductionPercent} % av utslippene mot 2040, men bare ${forgonePercent} % av produksjonen. ` +
        (reductionPercent > forgonePercent
          ? `Det betyr at du har truffet feltene med høyest utslipp per fat – smart utfasing!`
          : `Vil du ha mer klimaeffekt for produksjonstapet, bør du prioritere feltene med høyest utslippsintensitet.`),
    });
  }

  const summary =
    phasedOutFields.length === 0
      ? `Uten tiltak slipper norsk sokkel ut ${formatMt(baselineEmission)} CO₂ frem mot 2040. ` +
        `Til sammenligning kutter MDGs utfasingsplan ${mdgReductionPercent} % av dette. Velg felter for avvikling og se hva planen din kan utrette.`
      : `Planen din faser ut ${phasedOutFields.length} av ${stats.length} felter og unngår ${formatMt(avoidedEmission)} CO₂ frem mot 2040 – ` +
        `et kutt på ${reductionPercent} % fra dagens kurs. MDGs plan kutter til sammenligning ${mdgReductionPercent} %. ${gradeComment}`;

  return {
    grade,
    gradeComment,
    summary,
    insights,
    avoidedEmission,
    reductionPercent,
    mdgReductionPercent,
  };
}

/** Returns the field stats used by the advisor, exposed for UI tables. */
export function advisorFieldStats(): FieldStat[] {
  return computeFieldStats();
}
